import React from "react";
import figma from "@figma/code-connect";
import Button from "./Button";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/file/LkIyThUA0oVNsDEAyOF7ER/Design-System--Components?node-id=19%3A360",
  {
    props: {
      label: figma.string("Label"),
      appearance: figma.enum("Appearance", {
        Primary: "primary",
        Soft: "soft",
        Disabled: "disabled",
        Outline: "outline",
        Destructive: "destructive",
        Ghost: "ghost",
        Text: "text",
      }),
      layout: figma.enum("Layout", {
        "Label Only": "label-only",
        "Icon Right": "icon-right",
        "Icon Left": "icon-left",
        "Icon Only": "icon-only",
      }),
      size: figma.enum("Size", {
        XSmall: "xsmall",
        Large: "large",
        Default: "default",
        Small: "small",
      }),
    },
    example: (props) => <Button {...props} />,
  }
);
